name: denseclus
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - black
  - matplotlib
  - scikit-learn
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - hdbscan==0.8.27
  - umap-learn==0.5.1
  - seaborn
